name: Push Workflow
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Display message
        run: echo "First Work Flow"

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17' # Specify your required Java version
          distribution: 'temurin'
          cache: 'gradle' # Enables caching for Gradle dependencies

      - name: Run build in a subdirectory
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: 'build'

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4
        with:
            name: user-micro-service
            path: build/libs/*.jar

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.GIT_DOCKERHUB_USERNAME }}
            password: ${{ secrets.GIT_DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
            context: .
            push: true
            tags: ${{ secrets.GIT_DOCKERHUB_USERNAME }}/user-micro-service:latest